# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


# from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QSize, QMetaObject, QCoreApplication
from PyQt5.QtGui import QFont, QPixmap, QIcon, QCursor
from PyQt5.QtWidgets import QDialogButtonBox, QSizePolicy, QCommandLinkButton, QVBoxLayout, QFrame, QSpacerItem, \
    QLineEdit, QHBoxLayout, QCheckBox, QComboBox, QGroupBox, QTextBrowser, QWidget, QStatusBar, QProgressBar, \
    QPushButton, QToolButton


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 615)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(700, 615))
        MainWindow.setMaximumSize(QSize(1150, 730))
        MainWindow.setFocusPolicy(Qt.StrongFocus)
        icon = QIcon()
        icon.addPixmap(QPixmap(":/head.jpg"), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(2)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.funcLayout = QVBoxLayout()
        self.funcLayout.setObjectName("funcLayout")
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QSize(200, 350))
        self.textBrowser.setMaximumSize(QSize(9999, 9999))
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.funcLayout.addWidget(self.textBrowser)
        self.funcGroupBox = QGroupBox(self.centralwidget)
        self.funcGroupBox.setEnabled(True)
        self.funcGroupBox.setMinimumSize(QSize(670, 130))
        self.funcGroupBox.setMaximumSize(QSize(9999, 130))
        self.funcGroupBox.setObjectName("funcGroupBox")
        self.horizontalLayout_2 = QHBoxLayout(self.funcGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QFrame(self.funcGroupBox)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(180, 0))
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.chooseBox = QComboBox(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseBox.sizePolicy().hasHeightForWidth())
        self.chooseBox.setSizePolicy(sizePolicy)
        self.chooseBox.setMaximumSize(QSize(16777215, 70))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.chooseBox.setFont(font)
        self.chooseBox.setInputMethodHints(Qt.ImhNone)
        self.chooseBox.setObjectName("chooseBox")
        self.chooseBox.addItem("")
        self.chooseBox.addItem("")
        self.chooseBox.addItem("")
        self.verticalLayout_8.addWidget(self.chooseBox)
        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line_2 = QFrame(self.frame)
        self.line_2.setEnabled(True)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.checkisopen = QCheckBox(self.frame)
        self.checkisopen.setMaximumSize(QSize(16777215, 80))
        self.checkisopen.setObjectName("checkisopen")
        self.verticalLayout_5.addWidget(self.checkisopen)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addWidget(self.frame)
        self.line_3 = QFrame(self.funcGroupBox)
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame1 = QFrame(self.funcGroupBox)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_3 = QVBoxLayout(self.frame1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchinput = QLineEdit(self.frame1)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchinput.sizePolicy().hasHeightForWidth())
        self.searchinput.setSizePolicy(sizePolicy)
        self.searchinput.setMaximumSize(QSize(9999, 70))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.searchinput.setFont(font)
        self.searchinput.setFocusPolicy(Qt.StrongFocus)
        self.searchinput.setToolTip("")
        self.searchinput.setToolTipDuration(-1)
        self.searchinput.setFrame(False)
        self.searchinput.setClearButtonEnabled(True)
        self.searchinput.setObjectName("searchinput")
        self.verticalLayout_3.addWidget(self.searchinput)
        self.chooseinput = QLineEdit(self.frame1)
        self.chooseinput.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseinput.sizePolicy().hasHeightForWidth())
        self.chooseinput.setSizePolicy(sizePolicy)
        self.chooseinput.setMaximumSize(QSize(9999, 25))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.chooseinput.setFont(font)
        self.chooseinput.setFocusPolicy(Qt.NoFocus)
        self.chooseinput.setToolTip("")
        self.chooseinput.setToolTipDuration(-1)
        self.chooseinput.setMaxLength(25)
        self.chooseinput.setFrame(False)
        self.chooseinput.setCursorPosition(5)
        self.chooseinput.setClearButtonEnabled(True)
        self.chooseinput.setObjectName("chooseinput")
        self.verticalLayout_3.addWidget(self.chooseinput)
        self.horizontalLayout.addWidget(self.frame1)
        spacerItem = QSpacerItem(13, 20, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.line_4 = QFrame(self.funcGroupBox)
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.frame2 = QFrame(self.funcGroupBox)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setMaximumSize(QSize(90, 16777215))
        self.frame2.setObjectName("frame2")
        self.verticalLayout = QVBoxLayout(self.frame2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.next_btn = QCommandLinkButton(self.frame2)
        self.next_btn.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_btn.sizePolicy().hasHeightForWidth())
        self.next_btn.setSizePolicy(sizePolicy)
        self.next_btn.setMinimumSize(QSize(40, 30))
        self.next_btn.setMaximumSize(QSize(100, 40))
        self.next_btn.setSizeIncrement(QSize(0, 0))
        self.next_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.next_btn.setToolTip("")
        self.next_btn.setToolTipDuration(-1)
        self.next_btn.setStatusTip("")
        self.next_btn.setWhatsThis("")
        self.next_btn.setIconSize(QSize(50, 25))
        self.next_btn.setCheckable(False)
        self.next_btn.setChecked(False)
        self.next_btn.setAutoRepeat(False)
        self.next_btn.setAutoExclusive(False)
        self.next_btn.setAutoRepeatInterval(300)
        self.next_btn.setObjectName("next_btn")
        self.verticalLayout.addWidget(self.next_btn)
        self.retrybtn = QDialogButtonBox(self.frame2)
        self.retrybtn.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.retrybtn.sizePolicy().hasHeightForWidth())
        self.retrybtn.setSizePolicy(sizePolicy)
        self.retrybtn.setMinimumSize(QSize(20, 0))
        self.retrybtn.setMaximumSize(QSize(100, 16777215))
        self.retrybtn.setCursor(QCursor(Qt.ArrowCursor))
        self.retrybtn.setWhatsThis("")
        self.retrybtn.setOrientation(Qt.Horizontal)
        self.retrybtn.setStandardButtons(QDialogButtonBox.Retry)
        self.retrybtn.setObjectName("retrybtn")
        self.verticalLayout.addWidget(self.retrybtn)
        self.horizontalLayout.addWidget(self.frame2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.line_5 = QFrame(self.funcGroupBox)
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.verticalLayout_9 = QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.helpbtn = QToolButton(self.funcGroupBox)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpbtn.sizePolicy().hasHeightForWidth())
        self.helpbtn.setSizePolicy(sizePolicy)
        self.helpbtn.setMinimumSize(QSize(65, 60))
        self.helpbtn.setMaximumSize(QSize(65, 110))
        self.helpbtn.setCursor(QCursor(Qt.PointingHandCursor))
        self.helpbtn.setFocusPolicy(Qt.StrongFocus)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/help_btn.jpg"), QIcon.Normal, QIcon.Off)
        self.helpbtn.setIcon(icon1)
        self.helpbtn.setIconSize(QSize(65, 65))
        self.helpbtn.setCheckable(False)
        self.helpbtn.setChecked(False)
        self.helpbtn.setPopupMode(QToolButton.DelayedPopup)
        self.helpbtn.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.helpbtn.setAutoRaise(True)
        self.helpbtn.setArrowType(Qt.NoArrow)
        self.helpbtn.setObjectName("helpbtn")
        self.verticalLayout_9.addWidget(self.helpbtn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.funcLayout.addWidget(self.funcGroupBox)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.crawl_btn = QPushButton(self.centralwidget)
        self.crawl_btn.setEnabled(False)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.crawl_btn.setFont(font)
        self.crawl_btn.setToolTip("")
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/crawl_btn.jpg"), QIcon.Normal, QIcon.Off)
        self.crawl_btn.setIcon(icon2)
        self.crawl_btn.setIconSize(QSize(30, 30))
        self.crawl_btn.setCheckable(True)
        self.crawl_btn.setChecked(False)
        self.crawl_btn.setObjectName("crawl_btn")
        self.verticalLayout_2.addWidget(self.crawl_btn)
        self.progressBar = QProgressBar(self.centralwidget)
        font = QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.funcLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.funcLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        font = QFont()
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.helpbtn.clicked.connect(MainWindow.show_help)
        self.chooseBox.currentIndexChanged['int'].connect(self.searchinput.clear)
        QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.helpbtn, self.chooseBox)
        MainWindow.setTabOrder(self.chooseBox, self.next_btn)
        MainWindow.setTabOrder(self.next_btn, self.chooseinput)
        MainWindow.setTabOrder(self.chooseinput, self.checkisopen)
        MainWindow.setTabOrder(self.checkisopen, self.crawl_btn)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ComicSpider"))
        self.chooseBox.setItemText(0, _translate("MainWindow", "点选一个网站"))
        self.chooseBox.setItemText(1, _translate("MainWindow", "1、90MH"))
        self.chooseBox.setItemText(2, _translate("MainWindow", "2、KUKUdm"))
        self.checkisopen.setText(_translate("MainWindow", "下载完成后打开文件夹"))
        self.searchinput.setInputMask(_translate("MainWindow", "输入关键字：xxxxxxxxxx"))
        self.searchinput.setText(_translate("MainWindow", "输入关键字："))
        self.chooseinput.setStatusTip(_translate("MainWindow", "示例： 0 表示全选(特殊)   |   1 表示单选 1 (类推)   |   7+9 →表示多选 7、9 (加号)   |   3-5 →多选 3、4、5 (减号)"))
        self.chooseinput.setInputMask(_translate("MainWindow", "选择序号：####################"))
        self.chooseinput.setText(_translate("MainWindow", "选择序号："))
        self.next_btn.setText(_translate("MainWindow", "搜索"))
        self.retrybtn.setToolTip(_translate("MainWindow", "对内容不满意时重做上一步"))
        self.retrybtn.setStatusTip(_translate("MainWindow", "①书本列表出来后retry==重开软件 ②章节列表出来后retry==返回第①步的书列表重选  ▲ 多选书情况下慎用retry ▲"))
        self.helpbtn.setToolTip(_translate("MainWindow", ">_<"))
        self.helpbtn.setStatusTip(_translate("MainWindow", "挡住输出框了？再点一下"))
        self.helpbtn.setText(_translate("MainWindow", "我是说明\n"
">_<"))
        self.crawl_btn.setText(_translate("MainWindow", "开始爬取！"))
        self.progressBar.setToolTip(_translate("MainWindow", " ……悲哀，这进度条太难了, 总页数超100的话进度条失效 (Ｔ▽Ｔ)"))
        self.progressBar.setStatusTip(_translate("MainWindow", " ……悲哀，这进度条太难了, 总页数超100的话进度条失效 (Ｔ▽Ｔ)"))
