name: Bug Report 🐛
description: 创建 Bug 报告以帮助我们改进 / Create a report to help us improve
title: 🐛[BUG]
assignees:
  - jasoneri
labels: bug
body:
  - type: textarea
    attributes:
      label: 🐛 描述(Description)
      description: >-
        详细地描述 bug，让大家都能理解/Describe the bug in detail so that everyone can
        understand it
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📷 复现步骤(Steps to Reproduce)
      description: >-
        清晰描述复现步骤，让别人也能看到问题/Clearly describe the reproduction steps so that
        others can see the problem
      value: |-
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ' 📄 [异常/日志]信息([Exception/Log] Information)'
      description: 如报错等其他信息可以贴在这里，或上传log文件/Other information such as crash can be posted here, or upload log file
  - type: markdown
    attributes:
      value: '## 🚑 **基本信息(Basic Information)**'
  - type: input
    attributes:
      label: 程序哈希号(Program hash number)
      description: >-
        请填写当前程序的哈希号，绿色安装包可在`scripts/version`里获取 / Please enter the hash number of the
        current program, Portable version can find it from `scripts/version`
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 系统(OS)
      description: 在哪些系统中出现此问题/In which systems does this problem occur
      multiple: true
      options:
        - Windows10~+
        - Windows7~-
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📄 配置文件(Configuration file)
      description: "上传配置文件`scripts/conf.yml` 或 配置窗口的截图 (记得脱敏!!下面字段的值 删除或打马赛克 等手段模糊化)
      /Upload configure file`scripts/conf.yml` or configur dialog screenshots (remember desensitization!! The value of below field must be blur)"
      placeholder: >-
        储存路径, 代理，eh_cookies / sv_path, proxies, eh_cookies
  - type: textarea
    attributes:
      label: ' 🖼 其他截图(Screenshots)'
      description: 其他截图可以贴在这里/Screenshots of other situations can be posted here
