---
name: "Feature request \U0001F451"
description: 对程序的需求或建议 / Suggest an idea for program
title: "\U0001F451[标题这里简述需求或建议/Describe simply for suggest] "
labels: enhancement
body:
  - type: textarea
    attributes:
      label: 🥰 需求描述(Description)
      placeholder: 详细地描述需求，让大家都能理解/escribe the requirements in detail so that everyone can understand them
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🧐 解决方案(Solution)
      placeholder: 如果你有解决方案，在这里清晰地阐述/If you have a solution, explain it clearly here
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context/其他信息
      placeholder: 如截图等其他信息可以贴在这里/Other information such as screenshots can be posted here
    validations:
      required: false