import argparse
import pathlib
import re


UIC_DIR = pathlib.Path(__file__).parent.parent

REPLACE_MAP = {
    "QLineEdit": "LineEdit",
    "QTextBrowser": "TextBrowser",
    "QTextEdit": "TextEdit",
    "QComboBox": "ComboBox",
    "QCheckBox": "CheckBox",
    "QSpinBox": "CompactSpinBox",
    "QProgressBar": "ProgressBar",
}

PYSIDE6_WIDGET_IMPORT_BLOCK = re.compile(
    r"^from PySide6\.QtWidgets import \((?P<body>.*?)\)\r?\n",
    re.MULTILINE | re.DOTALL,
)
PYSIDE6_WIDGET_IMPORT_LINE = re.compile(
    r"^from PySide6\.QtWidgets import (?P<body>[^\n()]+)\r?\n",
    re.MULTILINE,
)
GENERATED_IMPORTS = (
    re.compile(r"^import material_ct_rc\r?\n", re.MULTILINE),
    re.compile(r"^from qfluentwidgets import .*\r?\n", re.MULTILINE),
)


class ConvertBase:
    def __init__(self, old, new,
        pre_substitutions=None, post_substitutions=None, class_replacements=None, custom_fluent_widgets=None, extra_import="",
    ):
        self.old = old
        self.new = new
        self.pre_substitutions = pre_substitutions or {}
        self.post_substitutions = post_substitutions or {}
        self.replacements = {**REPLACE_MAP, **(class_replacements or {})}
        self.fluent_widgets = sorted(set(self.replacements.values()) | set(custom_fluent_widgets or []))
        self.extra_import = extra_import.strip()
        with open(UIC_DIR.joinpath(old), "r", encoding="utf8") as file:
            self.content = file.read()

    def run(self):
        content = self.content
        for pattern in GENERATED_IMPORTS:
            content = pattern.sub("", content)
        content = self._apply_substitutions(content, self.pre_substitutions)
        content = self._replace_widget_constructors(content)
        content = self._apply_substitutions(content, self.post_substitutions)
        content = self._replace_qtwidgets_import(content)
        with open(UIC_DIR.joinpath(self.new), "w", encoding="utf8") as file:
            file.write(content)

    @staticmethod
    def _apply_substitutions(content, substitutions):
        for old, new in substitutions.items():
            content = content.replace(old, new)
        return content

    def _replace_widget_constructors(self, content):
        for origin, new in self.replacements.items():
            content = re.sub(rf"\b{origin}\(", f"{new}(", content)
        return content

    def _replace_qtwidgets_import(self, content):
        match = PYSIDE6_WIDGET_IMPORT_BLOCK.search(content) or PYSIDE6_WIDGET_IMPORT_LINE.search(content)
        if not match:
            raise ValueError(f"{self.old} is not generated by PySide6 uic: missing PySide6.QtWidgets import")

        qt_widgets = re.findall(r"\b[A-Z]\w*\b", match.group("body"))
        remaining_widgets = [widget for widget in qt_widgets if widget not in self.replacements]
        replacement = self._format_qtwidgets_import(remaining_widgets) + self._fluent_import()
        return content[: match.start()] + replacement + content[match.end():]

    @staticmethod
    def _format_qtwidgets_import(widgets):
        if not widgets:
            return ""
        rows = [widgets[index : index + 4] for index in range(0, len(widgets), 4)]
        lines = ["from PySide6.QtWidgets import ("]
        for row_index, row in enumerate(rows):
            line_items = []
            for item_index, widget in enumerate(row):
                is_last = row_index == len(rows) - 1 and item_index == len(row) - 1
                line_items.append(widget if is_last else f"{widget},")
            lines.append("    " + " ".join(line_items))
        lines[-1] += ")"
        return "\n".join(lines) + "\n"

    def _fluent_import(self):
        imports = ["from qfluentwidgets import " + ", ".join(self.fluent_widgets)]
        if self.extra_import:
            imports.append(self.extra_import)
        return "\n".join(imports) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="转换 PySide6 UIC 文件为 Fluent 风格")
    parser.add_argument("filename", help="要转换的 UI Python 文件名（不含路径）")
    args = parser.parse_args()

    file = f"{args.filename}.py"
    match args.filename:
        case "conf_dia":
            converter = ConvertBase(file, file,
                pre_substitutions={
                    "label_2 = QLabel": "label_2 = StrongBodyLabel",
                    "acceptBtn = QToolButton": "acceptBtn = PrimaryToolButton",
                    "cancelBtn = QToolButton": "cancelBtn = TransparentToolButton",
                },
                custom_fluent_widgets=["StrongBodyLabel", "TransparentToolButton", "PrimaryToolButton"],
            )
        case "browser":
            converter = ConvertBase(file, file,
                pre_substitutions={
                    "topHintBox = QToolButton": "topHintBox = TransparentToggleToolButton",
                    "ensureBtn = QToolButton": "ensureBtn = PrimaryToolButton",
                },
                post_substitutions={"addressEdit = LineEdit": "addressEdit = LinkEdit"},
                class_replacements={"QToolButton": "TransparentToolButton"},
                custom_fluent_widgets=["TransparentToolButton", "PrimaryToolButton", "TransparentToggleToolButton"],
                extra_import="from GUI.uic.qfluent.components import LinkEdit",
            )
        case _:
            converter = ConvertBase(file, file)
    converter.run()
